name: Deploy NestJS Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test

    - name: Build application
      run: npm run build

    - name: Deploy to production
      if: github.ref == 'refs/heads/main'
      env:
        NODE_ENV: production
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_DATABASE: ${{ secrets.DB_DATABASE }}
        PORT: ${{ secrets.PORT }}
        CORS_ORIGIN: ${{ secrets.CORS_ORIGIN }}
      run: |
        # Add your deployment commands here
        # Example: scp -r dist/* user@server:/path/to/deploy
        # Example: ssh user@server "cd /path/to/deploy && npm install --production"
        # Example: ssh user@server "pm2 restart your-app-name" 